# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTaskCreate(object):
    def setupUi(self, FormTaskCreate):
        FormTaskCreate.setObjectName("FormTaskCreate")
        FormTaskCreate.resize(608, 232)
        FormTaskCreate.setMinimumSize(QtCore.QSize(132, 132))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FormTaskCreate)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(FormTaskCreate)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_create = QtWidgets.QLabel(self.groupBox)
        self.label_create.setObjectName("label_create")
        self.verticalLayout.addWidget(self.label_create)
        self.label_2_create = QtWidgets.QLabel(self.groupBox)
        self.label_2_create.setObjectName("label_2_create")
        self.verticalLayout.addWidget(self.label_2_create)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_create = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_create.setText("")
        self.lineEdit_create.setObjectName("lineEdit_create")
        self.verticalLayout_2.addWidget(self.lineEdit_create)
        self.dateTimeEdit_create = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_create.setObjectName("dateTimeEdit_create")
        self.verticalLayout_2.addWidget(self.dateTimeEdit_create)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_create = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_2.addWidget(self.pushButton_create)
        self.pushButton_2_create = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2_create.setObjectName("pushButton_2_create")
        self.horizontalLayout_2.addWidget(self.pushButton_2_create)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(FormTaskCreate)
        QtCore.QMetaObject.connectSlotsByName(FormTaskCreate)

    def retranslateUi(self, FormTaskCreate):
        _translate = QtCore.QCoreApplication.translate
        FormTaskCreate.setWindowTitle(_translate("FormTaskCreate", "Создать задачу"))
        self.groupBox.setTitle(_translate("FormTaskCreate", "Создать задачу"))
        self.label_create.setText(_translate("FormTaskCreate", "Введите описание задачи"))
        self.label_2_create.setText(_translate("FormTaskCreate", "Выберите время"))
        self.pushButton_create.setText(_translate("FormTaskCreate", "Отменить"))
        self.pushButton_2_create.setText(_translate("FormTaskCreate", "Создать"))
