# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTaskEdit(object):
    def setupUi(self, FormTaskEdit):
        FormTaskEdit.setObjectName("FormTaskEdit")
        FormTaskEdit.resize(474, 303)
        FormTaskEdit.setMinimumSize(QtCore.QSize(132, 132))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FormTaskEdit)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(FormTaskEdit)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_edit = QtWidgets.QLabel(self.groupBox)
        self.label_edit.setObjectName("label_edit")
        self.verticalLayout.addWidget(self.label_edit)
        self.label_2_edit = QtWidgets.QLabel(self.groupBox)
        self.label_2_edit.setObjectName("label_2_edit")
        self.verticalLayout.addWidget(self.label_2_edit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_edit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_edit.setText("")
        self.lineEdit_edit.setObjectName("lineEdit_edit")
        self.verticalLayout_2.addWidget(self.lineEdit_edit)
        self.dateTimeEdit_edit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_edit.setObjectName("dateTimeEdit_edit")
        self.verticalLayout_2.addWidget(self.dateTimeEdit_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_edit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout_2.addWidget(self.pushButton_edit)
        self.pushButton_2_edit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2_edit.setObjectName("pushButton_2_edit")
        self.horizontalLayout_2.addWidget(self.pushButton_2_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(FormTaskEdit)
        QtCore.QMetaObject.connectSlotsByName(FormTaskEdit)

    def retranslateUi(self, FormTaskEdit):
        _translate = QtCore.QCoreApplication.translate
        FormTaskEdit.setWindowTitle(_translate("FormTaskEdit", "Создать задачу"))
        self.groupBox.setTitle(_translate("FormTaskEdit", "Создать задачу"))
        self.label_edit.setText(_translate("FormTaskEdit", "Описание задачи "))
        self.label_2_edit.setText(_translate("FormTaskEdit", "Время"))
        self.pushButton_edit.setText(_translate("FormTaskEdit", "Отменить"))
        self.pushButton_2_edit.setText(_translate("FormTaskEdit", "Ок"))
